# M5Stack に src/ の全ファイルをアップロードし、RTCをPCのローカル時刻に同期する
# 使い方: .\upload.ps1 COM5

param([Parameter(Mandatory)][string]$Port)

$src = "$PSScriptRoot\..\src"

# ── 現在時刻を先に取得（boot_time.py 生成と RTC 設定に使う） ──
$now  = Get-Date
$psWd = [int]$now.DayOfWeek
if ($psWd -eq 0) { $mpWd = 6 } else { $mpWd = $psWd - 1 }  # MicroPython: Mon=0..Sun=6
$yr = $now.Year; $mo = $now.Month;  $dy = $now.Day
$hh = $now.Hour; $mm = $now.Minute; $ss = $now.Second

# ── boot_time.py を生成（RTC未設定時のフォールバック時刻） ──
$bootContent = "# Auto-generated by upload.ps1 -- do not edit manually`n"
$bootContent += "FLASH_DT = ($yr, $mo, $dy, $mpWd, $hh, $mm, $ss, 0)  # JST`n"
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText((Join-Path $src "boot_time.py"), $bootContent, $utf8NoBom)
Write-Host "Generated boot_time.py  ($yr-$('{0:D2}' -f $mo)-$('{0:D2}' -f $dy) $('{0:D2}' -f $hh):$('{0:D2}' -f $mm):$('{0:D2}' -f $ss) JST)"

# ── ファイルをアップロード ──
$files = @("boot.py", "map_coords.py", "data.py", "schedule.py", "wifi_ntp.py", "boot_time.py", "main.py", "local_config.py")

foreach ($f in $files) {
    $local = Join-Path $src $f
    Write-Host "Uploading $f ..."
    mpremote connect $Port cp $local :$f
}

# ── M5Stack RTC を PC ローカル時刻 (JST) に同期 ──
Write-Host "Syncing RTC from PC time..."
$cmd = "import machine; machine.RTC().datetime(($yr,$mo,$dy,$mpWd,$hh,$mm,$ss,0))"
mpremote connect $Port exec $cmd
Write-Host "RTC set to $yr-$('{0:D2}' -f $mo)-$('{0:D2}' -f $dy) $('{0:D2}' -f $hh):$('{0:D2}' -f $mm):$('{0:D2}' -f $ss) (JST)"

Write-Host "Done. Press reset on M5Stack."
